### ISSUE TITLE
How to verify MFA later and not inline when doing bank login?

### ISSUE THREAD

**Issue by javierjulio** [synapsepay/SynapsePayRest-Ruby#55]
Unless I'm mistaken there doesn't seem to be a method for verifying MFA for a bank login at a later point. Meaning I won't have the MFA answer when submitting the request. I could create an instance of `SynapsePayRest::UnverifiedNode` myself with the necessary data and verify it but I figure this would be private? Would it be preferred here to have a dedicated method/API for this? Something like `user.verify_ach_us_node_mfa`?

**Comment by stevula** [comment]
I didn't think to add this, since there isn't a way to fetch the node MFA info from the API again without resubmitting the bank login details. But I suppose if you stored the MFA access_token, the user could return to enter the MFA answer at a later time.

`user.verify_ach_us_node_mfa` seems reasonable. I would have it create an instance of `UnverifiedNode` and call `unverified_node.answer_mfa`.

**Comment by javierjulio** [comment]
This was resolved by #69
